import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#d5ede0",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#000",
    marginBottom: 20,
  },
  image: {
    width: 300,
    height: 300,
    marginTop: 20,
    marginBottom: 40,
    borderRadius: 100,
    borderWidth: 5,
    borderColor: "white",
    overflow: "hidden",
  },
  button: {
    backgroundColor: "#4CAF50",
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 5,
    width: 150,
    height: 50,
    alignItems: "center",
    margin: 10,
  },
  textInButton: {
    color: "white",
    fontSize: 18,
    textAlign: "center",
    fontWeight: "bold",
  },
  text: {
    fontSize: 20,
    color: "green",
    fontWeight: "bold",
  },
  errorText: {
    fontSize: 20,
    color: "red",
    fontWeight: "bold",
  },
  input: {
    width: "80%",
    padding: 10,
    marginBottom: 15,
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: "white",
  },
  message: {
    marginTop: 15,
    fontSize: 16,
    fontWeight: "bold",
  },
  gifImage: {
    width: 300,
    height: 300,
    marginTop: 20,
    marginBottom: 40,
    borderRadius: 150,
    borderWidth: 10,
    borderColor: "white",
    overflow: "hidden",
  },
  startGameButton: {
    backgroundColor: "#4CAF50",
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 5,
    width: 250,
    height: 80,
    alignItems: "center",
    justifyContent: "center",
    margin: 10,
  },
  navButtons_ranking: {
    position: "absolute",
    right: 10,
    top: 20,
    backgroundColor: "#4CAF50",
    borderRadius: 5,
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  navButtons_personalranking: {
    position: "absolute",
    right: 10,
    top: 100,
    backgroundColor: "#4CAF50",
    borderRadius: 5,
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
  },

  textInNavButton: {
    color: "black",
    fontSize: 8,
    textAlign: "center",
  },
  imageInNavButtons: {
    width: 30,
    height: 30,
  },
  navButtons_user: {
    position: "absolute",
    left: 10,
    top: 20,
    backgroundColor: "#4CAF50",
    borderRadius: 5,
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  gameContainer: {
    flex: 1,
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  score: {
    fontSize: 20,
    marginBottom: 20,
  },
  gameGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  card: {
    width: 80,
    height: 80,
    margin: 6,
    backgroundColor: "#eee",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  cardImage: {
    width: 60,
    height: 60,
    resizeMode: "cover",
    borderRadius: 8,
  },
  timer: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FF3B30",
    marginBottom: 10,
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  item: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 0.5,
    borderColor: "#ccc",
  },
  position: {
    fontWeight: "bold",
    width: 30,
  },
  name: {
    flex: 1,
  },
  scoree: {
    fontWeight: "bold",
  },
  userSection: {
    marginTop: 30,
    borderTopWidth: 1,
    borderColor: "#ccc",
    paddingTop: 15,
  },
});

export default styles;
